# Generated by Django 5.1.4 on 2024-12-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyTree', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
