# Generated by Django 5.1.4 on 2024-12-31 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='familytree.company'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleets', to='familytree.company'),
        ),
        migrations.AlterField(
            model_name='part',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='familytree.fleet'),
        ),
    ]
